<?php

    namespace AppBundle\Repository;

    /**
    * ComponentRepository
    *
    * This class was generated by the Doctrine ORM. Add your own custom
    * repository methods below.
    */
    class ComponentRepository extends \Doctrine\ORM\EntityRepository
    {
    }
