<?php

namespace AppBundle\Repository;

/**
 * ComponentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentsRepository extends \Doctrine\ORM\EntityRepository
{
}
