<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComponentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentsRepository extends EntityRepository
{
    public function getRequestSql()
    {
        
    }
}
