<?php

namespace AppBundle\Repository;

/**
 * DashboardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardsRepository extends \Doctrine\ORM\EntityRepository
{
}
