<<<<<<< HEAD
<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
=======
<?php

    namespace AppBundle\Repository;

    /**
    * UserRepository
    *
    * This class was generated by the Doctrine ORM. Add your own custom
    * repository methods below.
    */
    class UserRepository extends \Doctrine\ORM\EntityRepository
    {
    }
>>>>>>> 360de5359e57b84b807162fd5d93000696dc3f61
