imports:
    - {resource: "@AppBundle/Resources/config/security.yml"}
security:
    role_hierarchy:
        ROLE_CREATOR:
          - ROLE_CREATOR
          - ROLE_USER
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:
          - ROLE_ADMIN
          - ROLE_CREATOR
          - ROLE_USER
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/admin_profile, role: ROLE_ADMIN }
        - { path: ^/user_profile, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }
