# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    
    app.charts:
        class: AppBundle\Charts\Charts
        arguments: [@app.SQLRequest]

    app.SQLRequest:
        class: AppBundle\SQLRequest\SQLRequest
        arguments: [@doctrine.orm.entity_manager]

    app.form.add.user:
         class: AppBundle\Form\UserType
         tags:
              - { name: form.type, alias: app_form_add_user }
