
app_login:
    path:     /login
    defaults: {_controller: AppBundle:App:login }

app_admin_profile:
    path:     /admin_profile
    defaults: { _controller: AppBundle:App:adminProfile }

app_user_profile:
    path:     /user_profile
    defaults: { _controller: AppBundle:App:userProfile }
