<<<<<<< HEAD
app_home:
    path:     /
    defaults: { _controller: AppBundle:Dashboard:index }

fos_user_security:
    path:     /login
    defaults: {_controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:     /login_check
    defaults: {_controller: FOSUserBundle:Security:check }

app_admin_profile:
    path:     /admin_profile/{id}
    defaults: { _controller: AppBundle:User:adminProfile }

app_user_profile:
    path:     /user_profile/{id}
    defaults: { _controller: AppBundle:User:userProfile }

#app_add_user:
#    path:     /admin_profile/{id}
#    defaults: { _controller: AppBundle:User:addUser }

#
app_edit_user:
    path:     /admin_profile/edit/{id}
    defaults: { _controller: AppBundle:User:editUser }

app_edit_users:
    path:     /admin_profile/edit/users{id}
    defaults: { _controller: AppBundle:User:editUsers }

app_dashboard:
    path:     /dashboard/{id}
    defaults: { _controller: AppBundle:Dashboard:view }

app_share_dashboard:
    path:     /dashboard/share/{id}
    defaults: { _controller: AppBundle:Dashboard:share }

app_delete_dashboard:
    path:     /dashboard/delete/{id}
    defaults: { _controller: AppBundle:Dashboard:deleteDash }

app_change_size:
    path:     /app_change_size/{componentId}/{size}/{id}
    defaults: { _controller: AppBundle:Dashboard:changeSize }

=======
>>>>>>> 360de5359e57b84b807162fd5d93000696dc3f61
app_add_component:
    path:     /components/{dashboardId}/add
    defaults: { _controller: AppBundle:Component:addComponent }
    requirements:
        componentId: \d+

app_edit_component:
    path:     /components/{componentId}/edit
    defaults: { _controller: AppBundle:Component:editComponent }
    requirements:
        componentId: \d+