app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_admin_dahboards:
    path:     /admin_dash_main
    defaults: { _controller: AppBundle:App:adminDashMain }

app_all_users:
    path:     /admin_dash/all_users
    defaults: { _controller: AppBundle:App: }