
app_home:
    path:     /
    defaults: { _controller: AppBundle:App:view }

#app_home:
#    path:     /dash
#    defaults: { _controller: AppBundle:App:Namedash }

#app_login:
#    path:     /login
#    defaults: {_controller: AppBundle:App:login }


app_share_dashboard:
    path:     /share
    defaults: { _controller: AppBundle:App:share }

app_admin_profile:
    path:     /admin_profile
    defaults: { _controller: AppBundle:App:adminProfile }


app_user_profile:
    path:     /user_profile
    defaults: { _controller: AppBundle:App:userProfile }

app_add_component:
    path:     /components/add
    defaults: { _controller: AppBundle:App:addComponent }

app_edit_component:
    path:     /components/{componentId}/edit
    defaults: { _controller: AppBundle:App:editComponent }
    requirements:
        componentId: \d+
#Route configuration FosUserBundle

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile