app_add_component:
    path:     /components/{dashboardId}/add
    defaults: { _controller: AppBundle:Component:addComponent }
    requirements:
        componentId: \d+

app_edit_component:
    path:     /components/{componentId}/edit
    defaults: { _controller: AppBundle:Component:editComponent }
    requirements:
        componentId: \d+