app_add_component:
    path:     /components/add
    defaults: { _controller: AppBundle:App:addComponent }

app_edit_component:
    path:     /components/{componentId}/edit
    defaults: { _controller: AppBundle:App:editComponent }
    requirements:
        componentId: \d+