app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_add_component:
    path:     /add_component
    defaults: { _controller: AppBundle:App:addComponent }

app_edit_component:
    path:     /edit_component
    defaults: { _controller: AppBundle:App:editComponent }