

#home
app_home:
    path:     /
    defaults: { _controller: AppBundle:Dashboard:index }

#Route Dashboard
app_dashboard:
    path:     /dashboard/{id}
    defaults: { _controller: AppBundle:Dashboard:view }
app_share_dashboard:
    path:     /share/{id}
    defaults: { _controller: AppBundle:Dashboard:share }

app_delete_dashboard:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Dashboard:deleteDash }
app_change_size:
    path:     /app_change_size/{componentId}/{size}/{id}
    defaults: { _controller: AppBundle:Dashboard:changeSize }
app_name_dashboard:
    path:     /yourdashboard
    defaults: {_controller: AppBundle:Navbar:NameDashboard }
#Route Profile User & Admin
app_admin_profile:
    path:     /admin_profile
    defaults: { _controller: AppBundle:User:adminProfile }
app_user_profile:
    path:     /user_profile
    defaults: { _controller: AppBundle:User:userProfile }

#Route Component
app_add_component:
    path:     /components/{dashboardId}/add
    defaults: { _controller: AppBundle:Component:addComponent }
    requirements:
        componentId: \d+
app_edit_component:
    path:     /components/{componentId}/edit
    defaults: { _controller: AppBundle:Component:editComponent }
    requirements:
        componentId: \d+



