services:
    app.charts:
        class: AppBundle\Charts\Charts
        arguments: [ @app.requestSql ]

    app.requestSql:
<<<<<<< HEAD
         class: AppBundle\RequestSql\RequestSql
         arguments: [@doctrine.orm.entity_manager]

    app.form.add.user:
         class: AppBundle\Form\UserType
         tags:
              - { name: form.type, alias: app_form_add_user }
=======
        class: AppBundle\RequestSql\RequestSql
        arguments: [ @doctrine.orm.entity_manager ]
>>>>>>> 360de5359e57b84b807162fd5d93000696dc3f61
