services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.charts:
        class: AppBundle\Charts\Charts
        arguments: [@app.requestSql]

    app.requestSql:
         class: AppBundle\RequestSql\RequestSql
         arguments: [@doctrine.orm.entity_manager]