services:
    app.charts:
        class: AppBundle\Charts\Charts
        arguments: [ @app.SQLRequest ]

    app.SQLRequest:
        class: AppBundle\SQLRequest\SQLRequest
        arguments: [ @doctrine.orm.entity_manager ]