services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.charts:
        class: AppBundle\Charts\Charts
        arguments: [@app.SQLRequest]

    app.SQLRequest:
        class: AppBundle\SQLRequest\SQLRequest
        arguments: [@doctrine.orm.entity_manager]

    app.form.add.user:
         class: AppBundle\Form\UserType
         tags:
              - { name: form.type, alias: app_form_add_user }